const header=document.querySelector('[data-header]')||document.querySelector('.site-header');
const menu=document.querySelector('.menu-btn');
const dot=document.querySelector('.cursor-dot');
window.addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>40),{passive:true});
menu?.addEventListener('click',()=>{if(!header)return;const open=header.classList.toggle('menu-active');document.body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>{header?.classList.remove('menu-active');document.body.classList.remove('menu-open');menu?.setAttribute('aria-expanded','false')}));
document.querySelectorAll('.footer a[href="#"]').forEach(a=>{const t=a.textContent.trim().toLowerCase();if(t==='impressum')a.href='impressum.html';if(t==='datenschutz')a.href='datenschutz.html';});
window.addEventListener('pointermove',e=>{if(dot){dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px'}},{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const choices={platz:{label:'Pflegeplatz',title:'Wir klären mit Ihnen, was wirklich wichtig ist.',text:'Pflegegrad, zeitlicher Bedarf, Zimmerwunsch und persönliche Situation – in einem ersten Gespräch bekommen Sie Orientierung statt Formularstress.',cta:'Rückruf anfragen'},angehoerig:{label:'Für Angehörige',title:'Sie müssen nicht schon alle Antworten kennen.',text:'Wir sortieren gemeinsam die nächsten Schritte – von Kosten und Pflegegrad bis zur Frage, wie ein Einzug konkret ablaufen kann.',cta:'Persönlich beraten lassen'},besuch:{label:'Walterhof kennenlernen',title:'Ein Pflegeheim sollte man nicht nur online beurteilen.',text:'Lernen Sie Atmosphäre, Wege und Menschen vor Ort kennen. Eine Besichtigung gibt oft mehr Sicherheit als jede Broschüre.',cta:'Besichtigung anfragen'}};
const panel=document.querySelector('[data-choice-panel]');document.querySelectorAll('[data-choice]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.choice-item').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const d=choices[btn.dataset.choice];if(!d||!panel)return;panel.animate([{opacity:.35,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:350,easing:'ease-out'});panel.innerHTML=`<p class="choice-label">${d.label}</p><h3>${d.title}</h3><p>${d.text}</p><a class="button light" href="#kontakt">${d.cta} <span>↗</span></a>`;}));
const story=document.querySelector('[data-story]');const steps=[...document.querySelectorAll('.story-step')];const y=document.querySelector('[data-story-year]');const copy=document.querySelector('[data-story-copy]');const progress=document.querySelector('[data-story-progress]');if(story&&steps.length){const update=()=>{const r=story.getBoundingClientRect();const total=story.offsetHeight-innerHeight;const p=Math.min(1,Math.max(0,-r.top/total));const idx=Math.min(steps.length-1,Math.floor(p*steps.length));const s=steps[idx];if(y&&y.textContent!==s.dataset.year){y.animate([{opacity:.2,transform:'translateY(15px)'},{opacity:1,transform:'none'}],{duration:320});y.textContent=s.dataset.year;copy.innerHTML=`<p>${s.dataset.kicker}</p><h3>${s.dataset.title}</h3><div>${s.dataset.text}</div>`;}if(progress)progress.style.width=(p*100)+'%'};addEventListener('scroll',update,{passive:true});update();}
