const header=document.querySelector('[data-header]');
const menu=document.querySelector('.menu-btn');
const dot=document.querySelector('.cursor-dot');
window.addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>40),{passive:true});
menu?.addEventListener('click',()=>{if(!header)return;const open=header.classList.toggle('menu-active');document.body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>{header?.classList.remove('menu-active');document.body.classList.remove('menu-open');menu?.setAttribute('aria-expanded','false')}));
document.querySelectorAll('.footer a[href="#"]').forEach(a=>{const t=a.textContent.trim().toLowerCase();if(t==='impressum')a.href='impressum.html';if(t==='datenschutz')a.href='datenschutz.html';});
window.addEventListener('pointermove',e=>{if(dot){dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px'}},{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.14});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));

// Existing Walterhof choice interaction
const choices={platz:{label:'Pflegeplatz',title:'Wir klären mit Ihnen, was wirklich wichtig ist.',text:'Pflegegrad, zeitlicher Bedarf, Zimmerwunsch und persönliche Situation – in einem ersten Gespräch bekommen Sie Orientierung statt Formularstress.',cta:'Pflege-Kompass starten'},angehoerig:{label:'Für Angehörige',title:'Sie müssen nicht schon alle Antworten kennen.',text:'Wir sortieren gemeinsam die nächsten Schritte – von Kosten und Pflegegrad bis zur Frage, wie ein Einzug konkret ablaufen kann.',cta:'Pflege-Kompass starten'},besuch:{label:'Walterhof kennenlernen',title:'Ein Pflegeheim sollte man nicht nur online beurteilen.',text:'Lernen Sie Atmosphäre, Wege und Menschen vor Ort kennen. Eine Besichtigung gibt oft mehr Sicherheit als jede Broschüre.',cta:'Besichtigung vormerken'}};
const panel=document.querySelector('[data-choice-panel]');
document.querySelectorAll('[data-choice]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.choice-item').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const d=choices[btn.dataset.choice];if(!d||!panel)return;panel.animate([{opacity:.35,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:350,easing:'ease-out'});panel.innerHTML=`<p class="choice-label">${d.label}</p><h3>${d.title}</h3><p>${d.text}</p><button class="button light" data-open-care>${d.cta} <span>↗</span></button>`;panel.querySelector('[data-open-care]')?.addEventListener('click',()=>openFlow('care'));}));

// Existing Walterhof history
const story=document.querySelector('[data-story]');const steps=[...document.querySelectorAll('.story-step')];const y=document.querySelector('[data-story-year]');const copy=document.querySelector('[data-story-copy]');const progress=document.querySelector('[data-story-progress]');if(story&&steps.length){const update=()=>{const r=story.getBoundingClientRect();const total=story.offsetHeight-innerHeight;const p=Math.min(1,Math.max(0,-r.top/Math.max(total,1)));const idx=Math.min(steps.length-1,Math.floor(p*steps.length));const s=steps[idx];if(y&&y.textContent!==s.dataset.year){y.animate([{opacity:.2,transform:'translateY(15px)'},{opacity:1,transform:'none'}],{duration:320});y.textContent=s.dataset.year;copy.innerHTML=`<p>${s.dataset.kicker}</p><h3>${s.dataset.title}</h3><div>${s.dataset.text}</div>`;}if(progress)progress.style.width=(p*100)+'%'};addEventListener('scroll',update,{passive:true});update();}

// Performance & visual pass: preconnect, optimized hero source and brighter treatment.
const preconnect=document.createElement('link');preconnect.rel='preconnect';preconnect.href='https://images.pexels.com';preconnect.crossOrigin='anonymous';document.head.appendChild(preconnect);
const hero=document.querySelector('.hero-photo');if(hero)hero.style.backgroundImage="url('https://images.pexels.com/photos/29372534/pexels-photo-29372534.jpeg?auto=compress&cs=tinysrgb&w=1600')";
const visualStyle=document.createElement('style');visualStyle.textContent=`
.hero-photo{filter:brightness(1.16) saturate(1.04)}
.hero-shade{background:linear-gradient(90deg,rgba(7,25,21,.67) 0%,rgba(7,25,21,.34) 42%,rgba(7,25,21,.04) 74%),linear-gradient(180deg,rgba(7,25,21,.12),transparent 35%,rgba(7,25,21,.42))!important}
.v2-launch{border:0;font:inherit}
.v2-bottom{display:none}
.v2-fab{position:fixed;right:22px;bottom:22px;z-index:1600;border:0;background:#f1e4d1;color:#15382f;border-radius:999px;padding:8px 14px 8px 8px;box-shadow:0 18px 60px rgba(4,24,19,.25);font-weight:800;cursor:pointer;align-items:center;gap:10px}
.v2-avatar{width:40px;height:40px;border-radius:50%;object-fit:cover;object-position:center;border:2px solid rgba(255,255,255,.72)}
.v2-overlay{position:fixed;inset:0;z-index:1800;background:rgba(5,20,16,.68);backdrop-filter:blur(14px);display:none;align-items:center;justify-content:center;padding:20px}
.v2-overlay.open{display:flex}
.v2-modal{width:min(760px,100%);max-height:min(820px,92vh);overflow:auto;background:#f5f0e8;color:#15382f;border-radius:28px;box-shadow:0 40px 120px rgba(0,0,0,.35);padding:28px;position:relative}
.v2-close{position:absolute;right:18px;top:18px;width:40px;height:40px;border:1px solid rgba(21,56,47,.15);border-radius:50%;background:transparent;font-size:1.3rem;cursor:pointer}
.v2-kicker{font-size:.66rem;text-transform:uppercase;letter-spacing:.14em;color:#6e7c75;font-weight:800}
.v2-modal h2{font-family:Georgia,serif;font-size:clamp(2.6rem,7vw,4.8rem);line-height:.95;letter-spacing:-.05em;font-weight:400;margin:12px 0 24px}
.v2-progress{height:3px;background:#d9ded9;border-radius:10px;margin:18px 0 28px;overflow:hidden}.v2-progress i{display:block;height:100%;background:#2d6656;transition:.35s;width:20%}
.v2-options{display:grid;gap:10px}.v2-option{width:100%;border:1px solid rgba(21,56,47,.17);background:#fff;color:#15382f;border-radius:15px;padding:17px 18px;text-align:left;font:inherit;font-weight:750;cursor:pointer;display:flex;justify-content:space-between;gap:12px}.v2-option:hover{border-color:#2d6656;transform:translateY(-1px)}
.v2-fields{display:grid;gap:13px}.v2-fields input{width:100%;padding:15px 16px;border:1px solid rgba(21,56,47,.17);border-radius:13px;background:#fff;font:inherit;color:#15382f}.v2-summary{background:#dfe8dc;border-radius:18px;padding:18px;margin:16px 0}.v2-summary small{display:block;text-transform:uppercase;letter-spacing:.11em;color:#65776e;margin-bottom:8px}.v2-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.v2-action{border:0;border-radius:999px;padding:14px 18px;background:#15382f;color:#fff;font:inherit;font-weight:800;cursor:pointer;text-decoration:none}.v2-action.secondary{background:#e2d4c0;color:#15382f}
.v2-chat{position:fixed;right:22px;bottom:82px;z-index:1700;width:min(390px,calc(100vw - 28px));max-height:72vh;background:#f5f0e8;color:#15382f;border-radius:24px;box-shadow:0 30px 100px rgba(0,0,0,.3);display:none;overflow:hidden}.v2-chat.open{display:block}.v2-chat-head{display:flex;align-items:center;gap:11px;padding:14px 15px;background:#15382f;color:#fff}.v2-chat-head .v2-avatar{width:44px;height:44px}.v2-chat-head strong{display:block}.v2-chat-head small{opacity:.72}.v2-chat-close{margin-left:auto;border:0;background:transparent;color:#fff;font-size:1.4rem;cursor:pointer}.v2-chat-body{padding:16px;overflow:auto;max-height:50vh}.v2-bubble{background:#fff;border-radius:15px 15px 15px 4px;padding:13px 14px;margin-bottom:12px;line-height:1.45}.v2-quick{display:flex;gap:7px;flex-wrap:wrap}.v2-quick button{border:1px solid rgba(21,56,47,.18);background:#fff;border-radius:999px;padding:9px 11px;color:#15382f;font:inherit;font-size:.78rem;font-weight:700;cursor:pointer}.v2-slots{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px}.v2-slots button{border:1px solid rgba(21,56,47,.15);background:#fff;border-radius:11px;padding:11px;font:inherit;cursor:pointer;color:#15382f}.v2-chat-note{font-size:.64rem;color:#6f7c76;padding:0 16px 14px}
@media(max-width:700px){.v2-fab{display:none}.v2-bottom{position:fixed;left:10px;right:10px;bottom:10px;z-index:1600;background:rgba(11,36,30,.95);backdrop-filter:blur(18px);border-radius:16px;padding:6px;display:grid;grid-template-columns:1fr 1fr 1fr;box-shadow:0 18px 60px rgba(0,0,0,.3)}.v2-bottom button{border:0;background:transparent;color:#fff;padding:11px 4px;font:inherit;font-size:.68rem;font-weight:800}.v2-bottom button+button{border-left:1px solid rgba(255,255,255,.12)}.v2-chat{right:10px;bottom:76px;max-height:78vh}.v2-modal{padding:22px 17px;border-radius:22px}.v2-modal h2{font-size:2.8rem}.v2-overlay{padding:10px}.v2-slots{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(visualStyle);

const maraImg='https://images.pexels.com/photos/7551614/pexels-photo-7551614.jpeg?auto=compress&cs=tinysrgb&w=180&h=180&fit=crop';
const ui=document.createElement('div');ui.innerHTML=`
<button class="v2-fab" data-mara><img class="v2-avatar" src="${maraImg}" alt="Symbolfoto der KI-Assistentin"><span>Mara fragen</span></button>
<div class="v2-bottom"><button data-care>Pflegeplatz</button><button data-job>Bewerbung</button><button data-mara>Mara</button></div>
<div class="v2-overlay" data-flow-overlay><div class="v2-modal"><button class="v2-close" data-flow-close aria-label="Schließen">×</button><div data-flow></div></div></div>
<div class="v2-chat" data-chat><div class="v2-chat-head"><img class="v2-avatar" src="${maraImg}" alt="Symbolfoto"><div><strong>Mara</strong><small>KI-Assistentin · keine Walterhof-Mitarbeiterin</small></div><button class="v2-chat-close" data-chat-close>×</button></div><div class="v2-chat-body"><div class="v2-bubble" data-chat-bubble>Hallo, ich bin Mara. Ich kann Ihnen bei Pflegeplatz, Kosten, Besichtigung und Jobs Orientierung geben – oder einen Gesprächstermin vormerken.</div><div class="v2-quick"><button data-chat-kind="care">Pflegeplatz</button><button data-chat-kind="cost">Kosten</button><button data-chat-kind="job">Jobs</button><button data-chat-kind="appointment">Termin</button></div><div data-slots></div></div><div class="v2-chat-note">Demo-Assistentin: keine medizinische Beratung und keine Zusage freier Plätze. Terminverfügbarkeit wird erst im Produktivsystem live abgeglichen.</div></div>`;
document.body.appendChild(ui);

let flowType='care',flowStep=0,flowData={};
const overlay=document.querySelector('[data-flow-overlay]');const flow=document.querySelector('[data-flow]');
function openFlow(type){flowType=type;flowStep=0;flowData={};overlay.classList.add('open');document.body.style.overflow='hidden';renderFlow();}
function closeFlow(){overlay.classList.remove('open');document.body.style.overflow='';}
function choose(key,val){flowData[key]=val;flowStep++;renderFlow();}
function flowHead(kicker,title,progress){return `<p class="v2-kicker">${kicker}</p><h2>${title}</h2><div class="v2-progress"><i style="width:${progress}%"></i></div>`}
function opts(list,key){return `<div class="v2-options">${list.map(([v,l,s])=>`<button class="v2-option" data-pick="${key}" data-val="${v}"><span>${l}${s?`<small style="display:block;font-weight:500;color:#6d7a74;margin-top:4px">${s}</small>`:''}</span><b>→</b></button>`).join('')}</div>`}
function bindPicks(){flow.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>choose(b.dataset.pick,b.dataset.val));}
function renderFlow(){if(!flow)return;if(flowType==='care')renderCare();else renderJob();}
function renderCare(){
 if(flowStep===0){flow.innerHTML=flowHead('Pflege-Kompass · 01/04','Für wen suchen Sie Unterstützung?',25)+opts([['angehoerig','Für einen Angehörigen','Ich organisiere die nächsten Schritte.'],['selbst','Für mich selbst','Ich möchte mich orientieren.']],'person');bindPicks();return;}
 if(flowStep===1){flow.innerHTML=flowHead('Pflege-Kompass · 02/04','Wie dringend ist die Situation?',50)+opts([['sofort','Sehr dringend','Wir brauchen schnell Orientierung.'],['wochen','In den nächsten Wochen','Wir planen den nächsten Schritt.'],['info','Erst einmal informieren','Noch keine konkrete Entscheidung.']],'urgency');bindPicks();return;}
 if(flowStep===2){flow.innerHTML=flowHead('Pflege-Kompass · 03/04','Ist ein Pflegegrad bekannt?',75)+opts([['bekannt','Ja'],['unklar','Noch nicht / unsicher']],'grade');bindPicks();return;}
 if(flowStep===3){flow.innerHTML=flowHead('Pflege-Kompass · 04/04','Wie dürfen wir Sie erreichen?',92)+`<div class="v2-fields"><input data-name placeholder="Vorname"><input data-contact placeholder="Telefon oder E-Mail"></div><div class="v2-actions"><button class="v2-action" data-submit>Zusammenfassung erstellen</button></div>`;flow.querySelector('[data-submit]').onclick=()=>{flowData.name=flow.querySelector('[data-name]').value||'–';flowData.contact=flow.querySelector('[data-contact]').value||'–';flowStep++;renderFlow()};return;}
 const next=flowData.urgency==='sofort'?'Persönlicher Rückruf möglichst zeitnah':flowData.urgency==='wochen'?'Besichtigung mit kurzem Vorgespräch':'Unverbindliches Orientierungsgespräch';flow.innerHTML=flowHead('Ihre Zusammenfassung','Der nächste Schritt ist klar.',100)+`<div class="v2-summary"><small>Smart Lead Summary</small><b>${next}</b><p>Für: ${flowData.person==='selbst'?'mich selbst':'Angehörige'} · Pflegegrad: ${flowData.grade==='bekannt'?'bekannt':'unklar'}<br>Kontakt: ${flowData.contact}</p></div><div class="v2-actions"><button class="v2-action" data-book>Gespräch vormerken</button><a class="v2-action secondary" href="tel:+4981213564">08121 3564 anrufen</a></div>`;flow.querySelector('[data-book]').onclick=()=>{closeFlow();openMara('appointment')};
}
function renderJob(){
 if(flowStep===0){flow.innerHTML=flowHead('60-Sekunden-Job-Match · 01/04','Welche Rolle passt zu dir?',25)+opts([['fachkraft','Pflegefachkraft'],['hilfe','Pflegehilfskraft'],['geronto','Gerontofachkraft'],['nacht','Dauernachtwache']],'role');bindPicks();return;}
 if(flowStep===1){flow.innerHTML=flowHead('Job-Match · 02/04','Wie möchtest du arbeiten?',50)+opts([['vollzeit','Vollzeit'],['teilzeit','Teilzeit'],['flexibel','Offen / flexibel']],'model');bindPicks();return;}
 if(flowStep===2){flow.innerHTML=flowHead('Job-Match · 03/04','Was ist dir besonders wichtig?',75)+opts([['plan','Planbarer Dienstplan'],['urlaub','30 Urlaubstage'],['entwicklung','Fort- & Weiterbildung'],['team','Kleines, vertrautes Team']],'priority');bindPicks();return;}
 if(flowStep===3){flow.innerHTML=flowHead('Job-Match · 04/04','Wie erreichen wir dich?',92)+`<p style="color:#65746d">Kein Anschreiben. Kein Lebenslauf im ersten Schritt.</p><div class="v2-fields"><input data-name placeholder="Vorname"><input data-contact placeholder="Telefon / WhatsApp oder E-Mail"></div><div class="v2-actions"><button class="v2-action" data-submit>Job-Match abschließen</button></div>`;flow.querySelector('[data-submit]').onclick=()=>{flowData.name=flow.querySelector('[data-name]').value||'–';flowData.contact=flow.querySelector('[data-contact]').value||'–';flowStep++;renderFlow()};return;}
 const role={fachkraft:'Pflegefachkraft',hilfe:'Pflegehilfskraft',geronto:'Gerontofachkraft',nacht:'Dauernachtwache'}[flowData.role];flow.innerHTML=flowHead('Dein erster Match','Das könnte passen.',100)+`<div class="v2-summary"><small>Bewerber-Summary</small><b>${role} · ${flowData.model}</b><p>Priorität: ${flowData.priority}<br>Kontakt: ${flowData.contact}</p></div><div class="v2-actions"><a class="v2-action" href="mailto:bewerbungen@pflegeheim-walterhof.de?subject=Kurzbewerbung%20Walterhof">Interesse senden</a><button class="v2-action secondary" data-book>Kennenlernen vormerken</button></div>`;flow.querySelector('[data-book]').onclick=()=>{closeFlow();openMara('appointment')};
}

document.querySelector('[data-flow-close]')?.addEventListener('click',closeFlow);overlay?.addEventListener('click',e=>{if(e.target===overlay)closeFlow()});document.querySelectorAll('[data-care]').forEach(b=>b.onclick=()=>openFlow('care'));document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>openFlow('job'));
document.querySelector('.header-cta')?.addEventListener('click',e=>{e.preventDefault();openFlow('care')});document.querySelector('.hero .button.primary')?.addEventListener('click',e=>{e.preventDefault();openFlow('care')});
if(location.pathname.includes('karriere')){const target=document.querySelector('.career-cta,.career-content,.jobs-head,main');if(target){const b=document.createElement('button');b.className='button primary v2-launch';b.textContent='60-Sekunden-Job-Match starten ↗';b.onclick=()=>openFlow('job');target.appendChild(b)}}

const chat=document.querySelector('[data-chat]');const bubble=document.querySelector('[data-chat-bubble]');const slots=document.querySelector('[data-slots]');
function openMara(mode){chat.classList.add('open');if(mode)chatAnswer(mode)}function closeMara(){chat.classList.remove('open')}
document.querySelectorAll('[data-mara]').forEach(b=>b.onclick=()=>openMara());document.querySelector('[data-chat-close]')?.addEventListener('click',closeMara);document.querySelectorAll('[data-chat-kind]').forEach(b=>b.onclick=()=>chatAnswer(b.dataset.chatKind));
function chatAnswer(kind){slots.innerHTML='';const text={care:'Für einen Pflegeplatz kann ich keine Verfügbarkeit versprechen. Ich kann Sie aber in wenigen Schritten durch den Pflege-Kompass führen.',cost:'Walterhof veröffentlicht eine Preisübersicht mit Stand 01.05.2026. Pflegegrad 2–5 ist dort mit 108,82 € täglichem Eigenanteil angegeben. Die individuelle Einordnung sollte persönlich erfolgen.',job:'Aktuell gibt es Recruiting-Signale für mehrere Pflege-Rollen. Der schnellste Einstieg ist unser 60-Sekunden-Job-Match.',appointment:'Gern. Wählen Sie einen Demo-Zeitslot für ein persönliches Gespräch. Im Produktivsystem würden diese Zeiten live mit dem Kalender abgeglichen.'}[kind]||'Wobei kann ich helfen?';bubble.textContent=text;if(kind==='care'){slots.innerHTML='<div class="v2-actions"><button class="v2-action" data-care-chat>Pflege-Kompass starten</button></div>';slots.querySelector('[data-care-chat]').onclick=()=>{closeMara();openFlow('care')}}if(kind==='job'){slots.innerHTML='<div class="v2-actions"><button class="v2-action" data-job-chat>Job-Match starten</button></div>';slots.querySelector('[data-job-chat]').onclick=()=>{closeMara();openFlow('job')}}if(kind==='appointment')renderSlots();}
function renderSlots(){const days=[];let d=new Date();while(days.length<3){d=new Date(d.getTime()+86400000);if(d.getDay()!==0&&d.getDay()!==6)days.push(new Date(d))}slots.innerHTML='<div class="v2-slots">'+days.flatMap(day=>['10:00','14:00'].map(t=>`<button data-slot="${day.toISOString().slice(0,10)} ${t}">${day.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'})}<br><b>${t}</b></button>`)).join('')+'</div>';slots.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{const chosen=b.dataset.slot;slots.innerHTML=`<div class="v2-summary"><small>Gewählter Termin</small><b>${chosen}</b><p>Demo-Vormerkung – noch keine echte Kalenderbuchung.</p></div><div class="v2-fields"><input data-chat-name placeholder="Ihr Name"><input data-chat-contact placeholder="Telefon oder E-Mail"></div><div class="v2-actions"><button class="v2-action" data-confirm>Termin vormerken</button></div>`;slots.querySelector('[data-confirm]').onclick=()=>{bubble.textContent='Danke. Im Produktivsystem wäre der Termin jetzt im Kalender reserviert und Sie würden eine Bestätigung erhalten.';slots.innerHTML='<div class="v2-summary"><b>Termin vorgemerkt ✓</b><p>Demo – keine Daten wurden übertragen.</p></div>'}})}

addEventListener('keydown',e=>{if(e.key==='Escape'){closeFlow();closeMara()}});
